Disable shadow-cljs due to conflict with Figwheel
```
----  Exception    ----
  No implementation of method: :-find-sources of protocol: #'cljs.closure/Compilable found for class: cljs.build.api$inputs$reify__6688
----  Exception Stack Trace  ----
java.lang.IllegalArgumentException: No implementation of method: :-find-sources of protocol: #'cljs.closure/Compilable found for class: cljs.build.api$inputs$reify__6688
 at clojure.core$_cache_protocol_fn.invokeStatic (core_deftype.clj:583)
    clojure.core$_cache_protocol_fn.invoke (core_deftype.clj:575)
    cljs.closure$eval45293$fn__45307$G__45284__45314.invoke (cljs_closure.clj:475)
    cljs.closure$build.invokeStatic (cljs_closure.clj:2707)
    cljs.closure$build.invoke (cljs_closure.clj:2672)
    cljs.build.api$build.invokeStatic (api.clj:208)
    cljs.build.api$build.invoke (api.clj:189)
    figwheel_sidecar.components.cljs_autobuild$cljs_build.invokeStatic (cljs_autobuild.clj:28)
```